### ISSUE TITLE
Cannot set maximum number of file

### ISSUE THREAD

**Issue by johnyang90** [peterfreeman/ngx-dropzone#10]
May I know how can I set the maximum number of files that can be uploaded?

**Comment by peterfreeman** [comment]
Hi,

this feature is currently not implemented. The native file input only allows to specify the `multiple` attribute. I recommend you to filter the files on your own in the `(filesAdded)` event:

```js
// in app.component.ts
onFilesAdded(files: File[]) 
{
  const maxNumberOfFiles = 4;
  const filesToUpload = files.slice(0, maxNumberOfFiles);
}
```

**Comment by johnyang90** [comment]
Thanks... it works now.
