### ISSUE TITLE
Support for files inside dragged directories

### ISSUE THREAD

**Issue by Dev-TT** [peterfreeman/ngx-dropzone#103]
when dragging/dropping a directory, it would be great to list all files inside, and also to list the files inside the subdirectories

**Comment by peterfreeman** [comment]
Hey there,

thanks for your feedback. I will consider it for the next major release.

Happy coding! 🤓

**Comment by harrizsb** [comment]
Hi!

Is there a way around to work on dragging and dropping a folder using ngx-dropzone?

Regards,

**Comment by peterfreeman** [comment]
Hi @harrizsb,

at the moment, I do not provide a workaround for this. The `webkitdirectory` attribute is still not standardized (see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#webkitdirectory)).
However, you are free to implement your own solution using this attribute.

Happy coding! 🤓
