### ISSUE TITLE
item image click not allow overwrite image

### ISSUE THREAD

**Issue by avilac3** [peterfreeman/ngx-dropzone#104]
when uploading an image and clicking on the preview you cannot overwrite the image only delete it
How can I avoid showing the option to load another new image on the image item 

My idea is to create a button inside <ngx-dropzone-label> but if I click it, it opens the option to upload another image by overwriting the current one. I don't want that. if I give out the loaded images yes

**Comment by peterfreeman** [comment]
Hey there,

I'm not sure whether I understood your question correctly but I think you have two options:
- Add an `event.preventDefault()` to your preview button click handler to prevent the click event from bubbling up to the dropzone component causing it to open the file explorer.
- Use the `[disableClick]` attribute on the `ngx-dropzone`. This prevents the file browser from opening up when clicking the dropzone or any child component overall.

Hope this helps, happy coding! 🤓

**Comment by avilac3** [comment]
thanks
the my solution was it 
use the 

<ngx-dropzone #drop></ngx-dropzone>
<button (click)="drop.showFileSelector()">Open</button>

Use the [disableClick] attribute on the ngx-dropzone
