### ISSUE TITLE
Original event available?

### ISSUE THREAD

**Issue by mattys31** [peterfreeman/ngx-dropzone#105]
Hi,

First issue and/or comment of any type on GitHub so please forgive me if it's dumb, but....

Using ngx-dropzone in a (change) function gives me an ngx-dropzone-event. I was wondering if there is a way to access the original event. The reason being that I want to be able to drag and drop things other than files into the dropzone. I know that's kinda against the idea, but I am collecting large lists of files and I don't want to keep them all in the browser. What I want to do is to be able to drag an icon representation of the file in the browser into the dropzone, have my server go fetch the files contents from an API, and then upload that. I still need the main drag and drop functionality but I wondered if i could be able to access datatransfer information from the original event to get a url from an image, then collect the files contents, and then continue with the upload.

Hope that makes sense.

Thanks

Matt

**Comment by peterfreeman** [comment]
Hi @mattys31,

unfortunately, I don't think you will get access to the original event as the dropzone overrides the `(change)` event.
What you could do is create custom "fake" files using the `File` API [(MDN link)](https://developer.mozilla.org/en-US/docs/Web/API/File).

Example:
```js
const fakeFile = new File(['some-random-content'], 'fakeFile.png', { type: 'image/png' })
```

Maybe this helps you?

Happy coding! 🤓
