### ISSUE TITLE
Loading icon appears

### ISSUE THREAD

**Issue by bayramerenn** [peterfreeman/ngx-dropzone#106]
When I try to upload the image, the icon is constantly being uploaded. Click anywhere on Dropzone and I can see the picture. He's hitting something but I don't understand

![image](https://user-images.githubusercontent.com/44176177/117292126-7ceac000-ae78-11eb-8370-a1916feb7103.png)

**Comment by kamalgharejeloo** [comment]
I have this problem too 

This is the data type (image/svg+xml) that I see in the photo for spinner , So the actual data type is the same as image/jpeg

When I click to select a new photo, the previous photo is displayed

**Comment by lhatrifork** [comment]
Had the same problem, be aware if you have change detection set to OnPush in a parent component
