### ISSUE TITLE
Can't reset input

### ISSUE THREAD

**Issue by tortap** [peterfreeman/ngx-dropzone#11]
Dropping the same file on the dropzone works fine, but if you click to open the hidden input, select one file do an upload on select, then try to upload the same file it will do nothing. It will not detect any change. There should be a way to reset the input so it can detect change (same file selected again).

**Comment by peterfreeman** [comment]
Hi,

thanks for your feedback. This is a common issue with the native file input element that I forgot to fix.
I updated the npm package so it should work now. 

Happy coding! 🤓
