### ISSUE TITLE
featured image

### ISSUE THREAD

**Issue by hamidh2** [peterfreeman/ngx-dropzone#111]
Is it possible to change of uploaded images order for a specific purpose?
Imagine we want to make the first image as a featured image for a user so we need to change the order of images by user drags on images that exist on the preview section!

**Comment by peterfreeman** [comment]
Hey there,

the order of the displayed (image) previews is depending on your `files: File[]` array.
The files get displayed using an `ngFor`-loop, so you only have to sort/reorder the array items based on your needs.

```html
<ngx-dropzone-preview *ngFor="let f of files">
    ...
</ngx-dropzone-preview>
```

I hope this helps you, happy coding! 🤓

**Comment by hamidh2** [comment]
Thank you peter
