### ISSUE TITLE
Label preview does not let me see the file size

### ISSUE THREAD

**Issue by 10iguel** [peterfreeman/ngx-dropzone#113]
I have seen that other versions on dropzone have the ability to preview not only name but also file size, since I can not find the size on the image uploaded, is there a way to display it on the preview?

**Comment by peterfreeman** [comment]
Hey @10iguel,

the `size` property is available on the `File` object, so you can simply read or display its value.
For more info see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/File).

Happy coding! 🤓
