### ISSUE TITLE
Images uploaded from mobile devices get rotated

### ISSUE THREAD

**Issue by radekjakubowski** [peterfreeman/ngx-dropzone#114]
Hello!
I am facing an issue in my project - while I am taking a photo with my mobile holding it vertically it gets uploaded but it is rotated by 90 degrees  as I guess to maintain correct aspect ratio.

Is there any workaround to make it work properly?

Here is my dropzone config:
![image](https://user-images.githubusercontent.com/83402116/123407096-df745880-d5ab-11eb-8b4c-aa8393ebe965.png)

I am looking forward for your reply!
Cheers,
Radek

**Comment by peterfreeman** [comment]
Hi @radekjakubowski,

are you sure you are using the dropzone from this repo? Your config properties don‘t seem to match..

Happy coding! 🤓

**Comment by radekjakubowski** [comment]
true that, I have written in wrong repo. Sorry for that. Keep up gr8 work!
