### ISSUE TITLE
upload completed event

### ISSUE THREAD

**Issue by aylmercarson** [peterfreeman/ngx-dropzone#115]
i've looked through the source but can't find such an event as output. if i drag half a dozen files onto the dropzone, it would be good to have a "completed" event exposed after all files have been uploaded?

**Comment by peterfreeman** [comment]
Hey @aylmercarson,

uploading files to an API endpoint is out of scope of this library. You will get an event when new files were dropped/selected and are available for preview or further processing (like uploading for example).

Happy coding! 🤓
