### ISSUE TITLE
How to hide Take Photo in iOS

### ISSUE THREAD

**Issue by VinodComlink** [peterfreeman/ngx-dropzone#116]
I want to hide take Photo option in iOS app. Is this feasible to loss this option?

**Comment by peterfreeman** [comment]
Hi @VinodComlink,

this option is defined by the HTML File API web standard and apparently [may not be changed](https://stackoverflow.com/questions/44678685/html-input-file-on-ios-app-disable-take-photo-option). This is out of scope of this library.

Happy coding! 🤓

**Comment by VinodComlink** [comment]
Thanks @peterfreeman
