### ISSUE TITLE
My file array is always empty.

### ISSUE THREAD

**Issue by halilpolathalil** [peterfreeman/ngx-dropzone#12]
The file list array always is empty. ı dont figure out why?Please help
Here is onFilesAdded method
```
onFilesAdded(files: File[]) {
    console.log("files");
    console.log(files);
    files.forEach(file => {
      const reader = new FileReader();

      reader.onload = (e: ProgressEvent) => {
        const content = (e.target as FileReader).result;

        // this content string could be used as an image source
        // or be uploaded to a webserver via HTTP.
        console.log(content);
      };

      // use this for basic text files like .txt or .csv
      reader.readAsText(file);

      // use this for images
      // reader.readAsDataURL(file);
    });
  }
```

And here is html code
 ```
<ngx-dropzone #dropzone  class="custom-dropzone"
              (filesAdded)="onFilesAdded($event)"
               [showImagePreviews]="true"
               [multiple]="true" 
               [label]=" 'COMMON.DROPANDDRAG' | translate "
               [maxFileSize]="1000"
               [[showPreviews]]="true"
               [accept]="'*'"
               [preserveFiles]="false" >
               </ngx-dropzone>
```

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback. I see several issues in your code:
- It would be helpful if you could look for any error messages in the console. 
- At first, you should make sure to use the latest version of the package. If you do it already, the property `[showImagePreviews]` doesn't exist anymore.
- For the `[label]` property use a valid expression: `label="{{ 'COMMON.DROPANDDRAG' | translate }}"`.
- The `[maxFileSize]` of 1000 bytes (=1kB) is pretty small, raise this value or remove it completely during testing.
- Only use single braces on `[showPreviews]`.

If none of this helps, remove all your HTML properties and start with a minimal configuration:
```html
<ngx-dropzone (filesAdded)="onFilesAdded($event)"></ngx-dropzone>
```

```js
onFilesAdded(files: File[]) {
  console.log(files);
}
```

From there on, you can add all of your properties one after the other and check the functionality in between to find out which property causes the error.

Happy coding! 🤓

**Comment by peterfreeman** [comment]
Seems like you have solved the issue, so I'm closing this.
