### ISSUE TITLE
Nativescript angular?

### ISSUE THREAD

**Issue by adammo14** [peterfreeman/ngx-dropzone#126]
Would ngx-dropzone work with Nativescript Angular?

If so, how would I go about adding this to my project? I've tried following the steps for Angular but an `<ngx-dropzone></ngx-dropzone>` element doesn't show up in the view. 

edit:

I've been tasked with replicating a functionality from a web app to a nativescript/angular app. This web app uses ngx-dropzone to pick an image and save it in a variable which gets passes into an api to be saved serverside.  I've tried to use `nativescript-imagepicker` to select an image but my endpoint rejects it because the data I'm passing is incorrect. My endpoint expects the file to be a `FormData` format and I've been trying to figure out what does `event.target.files` and `event.addedFiles` output to try and convert whatever I'm getting out of my imagepicker to be the same as web app. Would you be able to help please?

**Comment by peterfreeman** [comment]
The `addedFiles` output is nothing but a `File[]`, so essentially a `Blob[]`.
You can upload `Blob`s using `FormData`, see [this](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects#creating_a_formdata_object_from_scratch) example.
