### ISSUE TITLE
readFile() promise not being executed inside NgZone?

### ISSUE THREAD

**Issue by nicolas-garcia-kintai** [peterfreeman/ngx-dropzone#128]
Hello everyone,

I noticed there is some kind of problem when `readFile()` method is resolved.

I created a custom preview component where i preview image type files. But when an image type file is selected, the image preview is not being shown automatically, I have to explicitly detect changes using `ChangeDetectorRef` for the image preview to show up.

So I think that maybe the promise that handles the `FileReader` is not working correctly?
Is there a way to do this without using `ChangeDetectorRef`?

**Comment by peterfreeman** [comment]
Hi @nicolas-garcia-kintai,

this is a known issue, please refer to #95 for further info.
For now, please use the ChangeDetector, the next major update is still WIP.

Happy coding! 🤓
