### ISSUE TITLE
Deceiving FilesAdded

### ISSUE THREAD

**Issue by jingrah1** [peterfreeman/ngx-dropzone#13]
I've implemented the onFilesAdded event. However, instead of passing the newly added files, I get passed all files that are currently attached to the dropzone. Either I think this should be renamed to onFilesChanged or, ideally, implement both. That way you can get the added files when necessary, or receive all of them whenever any action is committed. Additionally, when multiple is false, the event is passing up the last file instead of failing the event.

I basically encapsulated this dropzone to fit better with our needs. I may try to clone and help make this more flexible. However, here is our encapsulation:

```javascript
export class DropzoneComponent {
    @Input('multiple') allowMultiple: boolean = true;
    @Output('filesAdded') filesAddedEmitter: EventEmitter<File[]> =
        new EventEmitter<File[]>();
    @Output('filesChanged') filesChangedEmitter: EventEmitter<File[]> =
        new EventEmitter<File[]>();
    @Output('fileRemoved') fileRemovedEmitter: EventEmitter<File> =
        new EventEmitter<File>();
    
    @ViewChild(NgxDropzoneComponent) dropzone: NgxDropzoneComponent;

    files: File[] = [];

    error: string = '';

    onFilesAdded(files: File[]): void {
        this.dropzone.reset();
        if (!this.allowMultiple) {
            if (files.length > 1) {
                this.error = "Cannot accept multiple files";
                return;
            } this.error = '';
            this.files = files;
        } else {
            this.files = this.files.concat(files);
        }

        this.filesAddedEmitter.emit(files);
        this.filesChangedEmitter.emit(this.files);
    }

    onFileRemoved(file: File): void {
        this.files = this.files.filter(function (value) {
            return value != file;
        });

        this.fileRemovedEmitter.emit(file);
        this.filesChangedEmitter.emit(this.files);
    }
}
```

We wrote our own custom list to call the onFileRemoved.

**Comment by peterfreeman** [comment]
Hey there,

thanks for your feedback. 
I think you need a very flexible and customized solution that goes beyond the needs of many other users. Therefore, I think you're better off using your custom implementation and I don't really see the need to implement the functionality in the main lib.

Of course, I'd highly appreciate a pull request from you to extend the lib.
Happy coding! 🤓

**Comment by peterfreeman** [comment]
Hi,

this still seems to be more of a very specific use case than an issue. Since you have found your own solution I will close this issue.

Happy coding! 🤓

**Comment by jingrah1** [comment]
Hello again!

I hate to be this guy, but I did actually put a couple of hours into reworking this today. However, it's a bit of a rewrite for most of the underlying code. Would you like me to still create a pull request? I know this is supposed to be a simplistic project, so if you prefer I create a separate repository on another fork, I can.

I can maybe just create a pull request when I get a little bit more done and then you guys can tell me whether or not I should continue on the path to completion? Admittedly, I rewrote a little bit of the UI as well to something that seemed more natural to me. I had a lot of problems getting the original UI to work properly with previews... :/

Let me know, thanks!

**Comment by peterfreeman** [comment]
Hi @jingrah1,

For now, I want to keep the API as simple as it is. I understand that you might need a more sophisticated dropzone solution, but that was never the intention of this package. I want to keep it simple and flexible, so users like you still have the option to customize it. 

Maybe I'll integrate your changes in the future or implement that functionality myself, but for now you're better off creating your own fork of the package. If you'd like I can add your repository to a list of maintained forks in the readme file.

Happy coding!

**Comment by jingrah1** [comment]
Hey @peterfreeman ,

Well, I mean, the API didn't change much besides being extended.. But, personally, I think it came out as being simpler (allowing for two-way binding). Also, it allows templates within the droparea and stuff. I was saying that the underlying service logic was rewritten to better fit the new extensions.

Either way, I created a fork. If you're interested in reviewing it, maybe we can merge them back together.. 

New fork: [https://github.com/jingrah1/ngx-dropzone](ngx-dropzone)

Otherwise, Happy coding!

**Comment by peterfreeman** [comment]
I just released v2 of the library which handles the file selection a bit different. This should resolve this issue.
