### ISSUE TITLE
Limit amount of files in DropZone

### ISSUE THREAD

**Issue by GiuliaAmaral** [peterfreeman/ngx-dropzone#130]
I'm using Dropzone to upload images and I need to limit the amount of images I upload to it, I want to limit it to 5 files. Has anyone done this or can you help me? ^_^

**Comment by peterfreeman** [comment]
Hi @GiuliaAmaral,

to limit the number of files, simply add a check to your `onSelect()` handler method.

```js
// in app.component.ts
limit = 5;
files: File[] = [];

onSelect(event) {
  const available = this.limit - this.files.length;
  this.files.push(...event.addedFiles.slice(0, available));
}
```

Happy coding! 🤓
