### ISSUE TITLE
Video thumbnail/image not appearing when file is uploaded

### ISSUE THREAD

**Issue by zacwillis** [peterfreeman/ngx-dropzone#136]
I am trying to upload a video that I dowloaded from Google Photos. It plays just fine on Google Photos and on my phone but when I upload it, the video doesn't play or have a thumbnail. I have attached an image of what it looks like. Any idea what would be causing this to happen?
<img width="1288" alt="Screen Shot 2021-12-21 at 4 26 50 PM" src="https://user-images.githubusercontent.com/36970370/147010819-a79208aa-48a5-42b6-8bd5-874a7ae2974c.png">

**Comment by peterfreeman** [comment]
Hi @zacwillis,

this library uses the `URL.createObjectURL(this.file)` Browser method to create a data string from the `File` object for display. Please test this method in isolation with your file. If it does not work, you can create your own preview component as described in the wiki.

Happy coding!
