### ISSUE TITLE
image preview does not work with svg

### ISSUE THREAD

**Issue by aliqb** [peterfreeman/ngx-dropzone#148]
when I upload  a svg image, preview does not show anything and chrome raises an error
![image](https://user-images.githubusercontent.com/46604616/163665207-bd55c46f-d25c-4435-bf6e-a981485e9515.png)
I set accept="image/*" 
I also tested "image/svg+xml" but none work

**Comment by phosph** [comment]
I sovle this issue by changing the line [the renderImage method on the component ngx-dropzone-image-preview](https://github.com/peterfreeman/ngx-dropzone/blob/master/projects/ngx-dropzone/src/lib/ngx-dropzone-preview/ngx-dropzone-image-preview/ngx-dropzone-image-preview.component.ts#L47) as follow:

``` typescript
private renderImage() {
    this.readFile()
      .then(img => setTimeout(() => {
        this.imageSrc = typeof img === "string"
          ? this.sanitizer.bypassSecurityTrustUrl(img)
          : this.imageSrc = img
      }))
      .catch(err => console.error(err));
  }
```

I created a new component in my app exactly as [the original one](https://github.com/peterfreeman/ngx-dropzone/blob/master/projects/ngx-dropzone/src/lib/ngx-dropzone-preview/ngx-dropzone-image-preview/ngx-dropzone-image-preview.component.ts) but with this small change.

**Comment by phosph** [comment]
I also had this problem and I was able to solve it by creating a new component in my app exactly like the original but but changing the renderImage method as follow:


I solve this issue by changing the line [the renderImage method on the component ngx-dropzone-image-preview](https://github.com/peterfreeman/ngx-dropzone/blob/master/projects/ngx-dropzone/src/lib/ngx-dropzone-preview/ngx-dropzone-image-preview/ngx-dropzone-image-preview.component.ts#L47) as follow:

``` typescript
private renderImage() {
    this.readFile()
      .then(img => setTimeout(() => {
        this.imageSrc = typeof img === "string"
          ? this.sanitizer.bypassSecurityTrustUrl(img)
          : this.imageSrc = img
      }))
      .catch(err => console.error(err));
  }
```

I created a new component in my app exactly as [the original one](https://github.com/peterfreeman/ngx-dropzone/blob/master/projects/ngx-dropzone/src/lib/ngx-dropzone-preview/ngx-dropzone-image-preview/ngx-dropzone-image-preview.component.ts) but with this small change.

**Comment by aliqb** [comment]
thanks its work
