### ISSUE TITLE
ngx-dropzone property [multiple] is not working

### ISSUE THREAD

**Issue by TonyGolem** [peterfreeman/ngx-dropzone#153]
Hi, 

the property [multiple]="false" is not working, 

the code: 

![image](https://user-images.githubusercontent.com/53716397/178314874-dd5e5130-d9f2-4f10-b9cc-80a62c5f0f0b.png)

the result:

![image](https://user-images.githubusercontent.com/53716397/178315149-e56f0995-2fdc-481c-8a2d-61f0cf8b2f69.png)

Angular CLI: 13.3.7
Node: 16.15.0
Package Manager: npm 7.5.6
OS: win32 x64
"ngx-dropzone": "^3.1.0"

**Comment by peterfreeman** [comment]
Hey there,
please show the code of your onSelect method.

**Comment by TonyGolem** [comment]
Hi, 

sure, here is my onSelect method.

![image](https://user-images.githubusercontent.com/53716397/180482570-af1b11a3-c332-451b-bbc4-75b3ca22825e.png)


I took it from the readme.md of the repository

**Comment by TonyGolem** [comment]
Hi, 

sure, here is my onSelect method.

![image](https://user-images.githubusercontent.com/53716397/180482570-af1b11a3-c332-451b-bbc4-75b3ca22825e.png)


I took it from the readme.md of the repository

Sorry, I accidentally closed the problem...

**Comment by peterfreeman** [comment]
Setting the `multiple` property to `false` only limits the number of files _per drop/selection_ to 1. If you always only want to show a single file, you have to implement this in your `onSelect` method.
In your case, you simply push all files to the `this.files` array and render them in the component, which will of course stack up to more than one file.
