### ISSUE TITLE
The 'Interpunct'-character seems not be supported in filenames 

### ISSUE THREAD

**Issue by sonnatager** [peterfreeman/ngx-dropzone#155]
Hi, 
I have following problem:
If i try to drop a file with the filename 'Test ⋅ .png' the change output gives back a file with empty filename.

Tried this on your DEMO page. First file is OK with filename 'Test.png' and second file is the file with the name mentioned above:

![2022-09-14_07-52_1](https://user-images.githubusercontent.com/37934901/190071047-61a0da12-a01d-475a-8cd8-8c8ec55e1ae1.png)

![2022-09-14_07-52](https://user-images.githubusercontent.com/37934901/190070863-2195189b-e16e-401b-9ac8-bd33b6ef4180.png)

There are also errors in the console:
![2022-09-14_07-57](https://user-images.githubusercontent.com/37934901/190071505-a5bb27aa-5e1d-488c-a3a4-80f21f890a96.png)

I think the problem is the interpunct ([Wiki](https://en.wikipedia.org/wiki/Interpunct)) in the filename.

**Comment by sonnatager** [comment]
Is this issue solved? Or not reproducible? Do you more information to fix it?

**Comment by peterfreeman** [comment]
@sonnatager Sorry, GitHub somehow omitted my comment. 
The reason for this behavior is indeed the invalid character in the file name. Please check out [this site](https://www.mtu.edu/umc/services/websites/writing/characters-avoid/) for reference.
The Browser falls back to an empty string, this is nothing the library can do anything about.
