### ISSUE TITLE
Relative Path and Recursive

### ISSUE THREAD

**Issue by arod1286** [peterfreeman/ngx-dropzone#156]
This is working beautifully with two exceptions:

- The webkitRelativePath is not returning any information
- Folder drop is not recursive. It only get files from the top directory.

I tried to get into the code to address it but it is over my level of experience.

progress: { value: number, fileName: string }[] = [];
theFiles: File[] = [];
  dropped(event: NgxDropzoneChangeEvent) {
    this.theFiles.push(...event.addedFiles);
    this.theFiles.forEach((e) => {
      this.progressInfos.push({ value: 0, fileName: e.webkitRelativePath + '/' + e.name + ' (' + (e.size / 1048576).toFixed(2) + " Mb)" });
    })
  }

**Comment by peterfreeman** [comment]
Hi there,

please use the `processDirectoryDrop` as written in the readme documentation to catch directories.
