### ISSUE TITLE
Files preview only works if the dropzone is clicked

### ISSUE THREAD

**Issue by juaparo** [peterfreeman/ngx-dropzone#17]
When I tried to upload multiple images, the dropzone is not displaying the preview immediately.

Have a nice day 👍🏻

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback. Do you have any more information for me to trace down the error?
What OS and browser are you using? Are there any errors in the console?

Happy coding! 🤓

**Comment by juaparo** [comment]
Hi  @peterfreeman ,

i found the bug in firefox browser and is happening when a drop the file in the dropzone the preview does not work but if i a clicked the dropzone the preview appears.

Additionaly the console does not diplaying errors.

Happy coding! 👾

**Comment by peterfreeman** [comment]
@juaparo Hi, could you please check whether this bug still persists in the latest version? I updated the library quite a bit and the way previews work now is very different.

Happy coding! 🤓

**Comment by MxMostafa** [comment]
Hi I install last version 2.0.3 
and I have the same problem
preview show only when click on dropzone
in chrome and angular 7

**Comment by MxMostafa** [comment]
please help me
how to show uploaded image?
my method return Image urls from server and most get image from server and push to files to show images? 
how to get image from url and convert to File to pusg to list ?

**Comment by peterfreeman** [comment]
> please help me
> how to show uploaded image?
> my method return Image urls from server and most get image from server and push to files to show images?
> how to get image from url and convert to File to push to list ?

@MxMostafa Please open a new issue for your question. This thread is about the display bug in Firefox which I'll have a look at in the next few days.

**Comment by peterfreeman** [comment]
@juaparo @MxMostafa 
I was not able to reproduce the error you're describing in Firefox. Could you try to replicate it using the basic [Stackblitz example](https://stackblitz.com/edit/ngx-dropzone) so we can be sure to use the same code base?

**Comment by pjbrigden** [comment]
Hi @peterfreeman, I have the same issue. I'm using Angular 8, and it's happening in Chrome, Firefox and Safari. Is there anything I can do to help you troubleshoot the issue? This component is really going to speed things up for me, so I am happy to help.

**Comment by pjbrigden** [comment]
A workaround I found which worked for me (not ideal but helps for now) is to do add detectChanges() in onSelect. E.g. my onSelect looks like this:

```
onSelect(event) {
    this.files.push(...event.addedFiles)
    setTimeout(()=>{ 
        this.changeDetectorRef.detectChanges()
    }, 150)
}
```
You may need to increase the timeout to make sure it doesn't run before the image is ready to be rendered.

**Comment by FelixEhuan** [comment]
@pjbrigden I have a custom preview using ```ngx-dropzone-image-preview``` and it's working fine only using the custom dropzone in my component  (Chrome and Firefox),
I'm using Angular 8 and  ngx-dropzone ^2.0.4

**Comment by peterfreeman** [comment]
Hey guys,

unfortunately, I still could not reproduce the error on my computer, but I tried to fix the problem by adding a `setTimeout()` callback on the image rendering function. This should trigger the Angular change detection without needing to use the `ChangeDetectorRef`.

```js
ngOnInit() {
    this.readFile()
      .then(img => setTimeout(() => this.imageSrc = img))
      .catch(err => console.error(err));
  }
```

I updated the [Stackblitz example](https://stackblitz.com/edit/ngx-dropzone) to v2.0.5. Could you please check if the problem still persists?

Happy coding! 🤓

**Comment by pjbrigden** [comment]
@peterfreeman I have tested with v2.0.5 and it doesn't look like it has solved the issue. If there is anything else I can do to help let me know.

**Comment by nikbabchenko** [comment]
> @peterfreeman I have tested with v2.0.5 and it doesn't look like it has solved the issue. If there is anything else I can do to help let me know.

If you can show the example) maybe it could help. 

p.s. maybe you have `Changedetection.OnPush` in your component?

**Comment by quangpdt** [comment]
For those who are still dealing with this problem, the root cause is because of `ChangeDetectionStrategy.OnPush` on your Component. Now you have 3 solutions to go:

1. Remove the `changeDetection: ChangeDetectionStrategy.OnPush` from your Component. It's not a good way but you don't have to modify the plugin.
2. Using `ChangeDetectorRef.markForCheck()` whenever adding/removing files from Dropzone. This could work but please notice, the Change detection will run for the whole component. Which is not good for your app performance.
3. Update this plugin by editing `DropzoneImagePreviewComponent`, `ngOnInit` function:

```ts
    public ngOnInit() {
        this.readFile()
            .then(img => {
                this.imageSrc = img;
                this.cd.markForCheck();
            })
            .catch(err => console.error(err));
    }
```

Now is your turn, choose the best way that suite you and Good luck ;)

**Comment by juaparo** [comment]
That's the solution for my thanks
