### ISSUE TITLE
If I upload the same file again its not calling the function 

### ISSUE THREAD

**Issue by Ge0f3** [peterfreeman/ngx-dropzone#18]
If I upload the same file again it's not calling the function 
for example, if I upload a file called xyz.csv it sends a requestion to the API and when I try to upload the same file xyz.csv again it's not even calling the angular function but when I try to upload a different file abc.csv its able to call the function and send the request.

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback. 
Do you select the file by dropping it on the zone or by using the file selector?

This was an issue in a previous version but it should be fixed now, please make sure to use the latest version.

Happy coding! 🤓

**Comment by Ge0f3** [comment]
Thank you it works now 

I did `npn uninstall  ngx-dropzone`

then npm install --save ngx-dropzone

so it pulled the latest version and now it works 

Thank you :)
