### ISSUE TITLE
Reactive forms support

### ISSUE THREAD

**Issue by chirag-sa** [peterfreeman/ngx-dropzone#19]
What if I want to attach formcontrol to ngx-dropzone and validate it

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback. This is not possible at the moment.
I'll add this feature request to my ToDo list and see if I can find the time to implement it.

Happy coding!

**Comment by peterfreeman** [comment]
I just released v2 of the library which handles the file selection a bit different. This resolves this issue.

**Comment by rubenheymans** [comment]
how do I use it with reactive forms?

**Comment by W5oAmI** [comment]
How can i attach a formcontrolName to ngx-dropzone and validate ?
