### ISSUE TITLE
Accept type not working for custom content

### ISSUE THREAD

**Issue by vigneshsithirai** [peterfreeman/ngx-dropzone#2]
While using the custom content, accept type is not working.

**Comment by vigneshsithirai** [comment]
Accept type for CSV file not working

**Comment by peterfreeman** [comment]
Hi,
do it like this:
```html
<ngx-dropzone [accept]="'text/csv'"></ngx-dropzone>
```

Works fine. 🤓

**Comment by vigneshsithirai** [comment]
Hi,
Thanks for your reply. I tried that also while opening the file browser its
shows CSV files only. But the file didn't get uploaded. In (filesDropped)
in dint get the files array.

Thanks,
Vignesh

**Comment by peterfreeman** [comment]
Sorry, but even after several tries I cannot reproduce your problem.
Using the following code, I get an array of files when dropping them on the drop zone or selecting them from the file browser:
```html
<ngx-dropzone [accept]="'text/csv'" (filesDropped)="onFilesDropped($event)"></ngx-dropzone>
```
