### ISSUE TITLE
Uncaught Error: No URL provided.

### ISSUE THREAD

**Issue by ajlonsdale** [peterfreeman/ngx-dropzone#20]
Dropzone seems to be working fine but i have this error in my console with no options to set the URL. 

In my case the URL is not needed but having the error in my console is not great

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback.
Could you please post all of the code you use concerning the dropzone?
What file (name/type/size) are you dropping?

Happy coding! 🤓

**Comment by ajlonsdale** [comment]
Hi, unfortunately i have had to move onto a different plugin so no longer have the code for this.

It was however the basic setup only using <ngx-dropzone></ngz-dropzone>  and the error message was displayed before trying to upload anything.

I've used dropzone before and i know you need to specify a URL otherwise it will display this message however there is no option to specify an upload URL.

I'll keep an eye out here because i like the implementation of your version i just don't want the console errors.

Let me know if you need anymore info!
