### ISSUE TITLE
Nested elements support

### ISSUE THREAD

**Issue by Bertramp** [peterfreeman/ngx-dropzone#21]
Really nice component! 
Something that would enhance the usability of it greatly imo would be to allow for nested elements. Then a custom section of a page or another component can suddenly become a dropzone

**Comment by peterfreeman** [comment]
Hey there,

thanks for your feedback.
That's a great idea. I'm currently planning a bigger update to the library which will also include other feature requests. I'll see if I can take your proposal into account. 

Happy coding!

**Comment by Bertramp** [comment]
Sounds great, looking forward to the update! 
I've played around with it a little, and I found it pretty easy to just present the dropzone as an attribute directive to get this functionality, the code is almost identical that of the component, so having both in the package doesn't seem like too much of a hassle. Just an idea to keep in mind if you're already planning a big update

Happy coding!

**Comment by a-bradaric** [comment]
My bad for going a bit off topic here, but when do you think we can expect your next major release, @peterfreeman?
We're seriously considering using your upload tool for our project and it would be great if your next release included features such as deleting single files or displaying the uploaded files as a list.

Great work by the way! :)

**Comment by peterfreeman** [comment]
@a-bradaric Thank you, I'm glad you like my work! :)

Unfortunately, I don't have much time right now because I'm moving to a new city. I think it will take at least another four weeks before I can really start working on the new features and you can see some results. Make sure to check back later!

Happy coding! 🤓

**Comment by peterfreeman** [comment]
I just released v2 of the library which includes this feature.
