### ISSUE TITLE
Scroll functionality is not working properly while dragging files.

### ISSUE THREAD

**Issue by krishragu12395** [peterfreeman/ngx-dropzone#22]
I have used ngx-dropzone for the uploading files in my application. That is working great but while I am dragging(top of my screen) the files which are presented on bottom of my home page browser's scroll is not working.

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback. Unfortunately, I do not understand your problem's description.
Are you sure this has something to do with the dropzone component?
Could you provide a gif or else for demonstration?

Happy coding! 🤓

**Comment by peterfreeman** [comment]
Seems like you have solved the issue.
