### ISSUE TITLE
How can i preserve file with condition

### ISSUE THREAD

**Issue by jigneshInd** [peterfreeman/ngx-dropzone#24]

**Comment by peterfreeman** [comment]
Hi there,

can you please provide more information on what you're trying to achieve?

**Comment by jigneshInd** [comment]
If i have uploaded one valid file and then upload some invalid file like maxsize exceed with preseve file false option, it removes exsting file, so if file is invalid then i want to not to remove exsting file.

**Comment by peterfreeman** [comment]
I just released v2 of the library which handles the file selection a bit different so you should be able to use it as you like now.
