### ISSUE TITLE
showPreviews not working

### ISSUE THREAD

**Issue by emrade** [peterfreeman/ngx-dropzone#25]
I just installed this plugin on an angular 8 project but the show preview does not work. When i upload an image, nothing happens at all. Nothing to show that the image was uploaded. Although, it's logged in the console.

`<ngx-dropzone [showPreviews]="true"
                                                (filesAdded)="onFilesAdded($event)"
                                            ></ngx-dropzone>`.
Help please?..

**Comment by peterfreeman** [comment]
Hey there,

thanks for your feedback. I didn't test it with Angular 8 yet and will do it asap.
What file type are you uploading? Jpeg, png..?

**Comment by emrade** [comment]
I tried different file formats, png, jpg, jpeg and even mp4

**Comment by capynet** [comment]
Adding `[showPreviews]="true"` Y got the preview on Angular 8.0.1
![image](https://user-images.githubusercontent.com/1402913/61936320-c6f8ff00-af8c-11e9-9946-f247cd5941c7.png)

**Comment by peterfreeman** [comment]
@capynet  Thanks for the verification, could you please post all of your code so @emrade can compare it to his?

**Comment by capynet** [comment]
```
<ngx-dropzone
  class="image-uploader"
  [showPreviews]="true"
  [accept]="'image/png,image/jpeg'"
  [multiple]="false"
  (filesAdded)="onFileAdded($event)"
></ngx-dropzone>
```

There you are.

**Comment by emrade** [comment]
```
<ngx-dropzone 
     [maxFileSize]="2000" 
     [showPreviews]="true"
     [accept]="'image/png,image/jpeg,image/jpg'"
     (filesAdded)="onFilesAdded($event)"
     (filesRejected)="onFilesRejected($event)"
></ngx-dropzone>
```

And that is what mine looks like?

**Comment by peterfreeman** [comment]
@emrade Could it be that the maximum file size is too small and you're seeing the output from the `fileRejected` event in the console? Could you please remove the `[maxFileSize]` for testing?

**Comment by emrade** [comment]
i followed your instruction and removed the maxFileSize and it actually worked. Thanks so much. But then what if i want to restrict the file size?

Also, for every image i upload it gives a lot of padding on both sides, is there any way i can reduce the padding?

Also is it possible to delete an image i have already dropped in? I dont really see a delete button.

**Comment by peterfreeman** [comment]
You can in fact restrict the file size, but the provided number will be bytes. So 2000 are actually 2kb, which is pretty small.

The padding depends on the image's aspect ratio, you could try to override the css classes.

Currently, it's not possible to delete single files but I'm working on a bigger update atm which will include this feature. I try to publish it within the next two weeks, check the v2 branch for current progress if you're interested.
