### ISSUE TITLE
Support multiple mimetypes and file extensions in accept property

### ISSUE THREAD

**Issue by thammerl** [peterfreeman/ngx-dropzone#26]
It's currently only possible to specify a single mimetype (resp. mimetype wildcard) in the `accept` input property. This is very limiting because different platforms use different mimetypes for the same file format. For example, some Windows systems report `application/vnd.ms-excel` instead of `text/plain` for CSV files. There's no way to support this using npx-dropzone.

The [input accept attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#accept) also supports specifying file extensions. File selectors will then only list files with the specified extensions. There's also no way to use this browser feature with npx-dropzone.

It should be possible to specify any comma separated list of [unique file type specifiers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Unique_file_type_specifiers) in the accept property. For example,...

```
accept="text/csv,text/tsv,.csv,.tsv"
```

...should accept any CSV or TSV file as long as it either matches by mimetype or by file extension.

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback. I'm currently working on v2 of this library and will try to add your feature request.

Happy coding! 🤓

**Comment by thammerl** [comment]
Hi @peterfreeman,

do you think it's possible to merge [my pull request](https://github.com/peterfreeman/ngx-dropzone/pull/27) and build one last v1 release? The existing tests pass and I've added additional tests for the enhancement.

**Comment by peterfreeman** [comment]
Hi @thammerl,

I've created the branch [ngx-dropzone-v1-archived](https://github.com/peterfreeman/ngx-dropzone/tree/ngx-dropzone-v1-archived) to keep v1 available and merged your pull request.
Feel free to also contribute to v2. :)

Happy coding! 🤓

**Comment by thammerl** [comment]
@peterfreeman Thanks. I've ported the change to v2. See #31.
