### ISSUE TITLE
Retrieve Data

### ISSUE THREAD

**Issue by nwwd** [peterfreeman/ngx-dropzone#3]
Hi is there any way to retrieve the data of the file being uploaded in the onFilesDropped function.

Also is there a way to display dropped files in the dropzone area?

Thanks

**Comment by nwwd** [comment]
Hi i used FileReader to solve issue one.

Issues 2 i am thinking ill use a custom array to hold the file names while i upload them to my api and display the names of the files on the template, it would be good if you could get something into the library for this functionality though.

Btw you library is nice and lightweight to use, thanks for sharing.

**Comment by nwwd** [comment]
Hi i used FileReader to solve issue one.

Issues 2 i am thinking ill use a custom array to hold the file names while i upload them to my api and display the names of the files on the template, it would be good if you could get something into the library for this functionality though.

side note - your library is nice and lightweight to use, thanks for sharing.

**Comment by peterfreeman** [comment]
Hi there,
thanks for the feedback.
Since I've got a lot of feature requests to add image previews I added them with the latest version.
Check it out! 🤓
