### ISSUE TITLE
After adding and removing one file, the change event is not triggered when re-adding the exact same file.

### ISSUE THREAD

**Issue by JDouven** [peterfreeman/ngx-dropzone#30]
I can replicate this in your example stackblitz.

1. Add file
2. Remove file
3. Try to add file again

The file will not be in the `files` array because onSelect did not get called.

**Comment by mrejmicz** [comment]
I have the same issue. Angular 8

**Comment by peterfreeman** [comment]
Fixed in v2.0.3. 

Happy coding! 🤓
