### ISSUE TITLE
How can we know why file rejected?

### ISSUE THREAD

**Issue by jigneshInd** [peterfreeman/ngx-dropzone#34]
How can we check reason for file rejection, like wrong file size or invalid file type?

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback. Currently, there is no explicit error message to why the file got rejected.
I will put it on the ToDo list and add a reason per file.
Of course, if you'd like to add this feature yourself, a pull request would be highly appreciated.

Happy coding! 🤓

**Comment by peterfreeman** [comment]
@jigneshInd I added this feature in v2.1.0. Each file in the `rejectedFiles` array now contains a `reason` property. See the readme for details.

The property is optional, so it should not be a breaking change for existing implementations.
Happy coding! 🤓

**Comment by jigneshInd** [comment]
@peterfreeman Thanks for adding this feature!

**Comment by strizzwald** [comment]
@peterfreeman The `rejectedFiles` property is of type `File[]` and not `RejectedFile[]` as mentioned in the documentation.

To get the `reason` property I'm casting to `any`

ngx-dropzone version used: `3.0.0`

![image](https://user-images.githubusercontent.com/9006589/111744974-b0579800-8894-11eb-8e11-1275d7c8158d.png)
