### ISSUE TITLE
How to get Dropzone.js instance?

### ISSUE THREAD

**Issue by itmjwj** [peterfreeman/ngx-dropzone#35]
How do I get a Dropzone instance for full API access? I would like to reset the dropzone view after I've manually uploaded all files.

**Comment by peterfreeman** [comment]
Hi there,

if you've used the dropzone as shown in the example, you can just clear your file array to remove all previews.

```js
// in app.component.ts
files: File[] = [];

onSelect(event) {
  this.files.push(...event.addedFiles);
}

reset() {
  this.files = [];
}
```

Does this answer your question?

**Comment by itmjwj** [comment]
Thank you. 
This is exactly what i need. Somehow i completely missed that.
Sorry for the inconvenience.

**Comment by peterfreeman** [comment]
No problem.🤓

**Comment by sfratini** [comment]
Sorry to bump this but I have another use case. I would like to use the displayExistingFile method so I would need the Dropzone class exposed somehow. Is this possible? @peterfreeman
