### ISSUE TITLE
Multiple false option not working properly.

### ISSUE THREAD

**Issue by jigneshInd** [peterfreeman/ngx-dropzone#36]
I have added [multiple]="false" option but it still allows me to add files when I add files one by one instead of overwriting existing and also is there any option for [preserveFiles]="false" like the previous version in the new version?

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback. This behaviour is intended as the outer dropzone component does not count the number of files it displays. If you want to preserve your existing file(s), just modify your `onSelect()` function. I tried to keep this as extensible as possible, so the consumer (you) can modify everything to his needs.

Example:
```js
// in app.component.ts
files: File[] = [];

onSelect(event) {
  if (this.files.length === 1) {
    return;
  }

  this.files.push(...event.addedFiles);
}
```
