### ISSUE TITLE
maxFileSize option not works proper!

### ISSUE THREAD

**Issue by jigneshInd** [peterfreeman/ngx-dropzone#38]
When I set [maxFileSize]="1000000" to allow 1mb file size limit still not allows files below 1mb and shows in rejected files array, can you please help on this

**Comment by peterfreeman** [comment]
Hey there,

thanks for your feedback. I tried to replicate your error in the [Stackblitz example](https://stackblitz.com/edit/ngx-dropzone) but for me everything worked fine.
Could you please try to reproduce the error using the example and post your exact code, the file size you used and any console messages?

Happy coding! 🤓

**Comment by codeninja93** [comment]
@jigneshInd i've used `[maxFileSize]="'1000000'"` passing value as string and it is working.

**Comment by peterfreeman** [comment]
Yes, you have to use either `[maxFileSize]="'1000000'"` or `maxFileSize="1000000"`.
Then it won't see your number as a variable.

**Comment by Never7Dice** [comment]
1MB in windows is actually 1MiB so it is '1048576' bytes.
