### ISSUE TITLE
Loading spinner

### ISSUE THREAD

**Issue by carminemilieni** [peterfreeman/ngx-dropzone#39]
Is possible implementing loading spinner?

**Comment by peterfreeman** [comment]
Hey there,

thanks for your feedback. You mean a loading spinner on each file preview?
I'll put that on my ToDo list.

Happy coding! 🤓

**Comment by KOSSOKO** [comment]
@peterfreeman not on the preview but during the image loading. I load for example 64 Gb using the dropzone, but before the end of the process, the user can't see that the image is loading.
Another example, when the image is on onSelectImage(event) for example, I send this image to the server. During the process I want to show a spinner on the image.

It could be great to have for each ngx-dropzone a variable. When activated (set to true) it shows the loading spinner. And when desactivated (set to false), it hidde the loading spinner.

**Comment by keyone2693** [comment]
https://github.com/peterfreeman/ngx-dropzone/pull/84

**Comment by peterfreeman** [comment]
Fixed in #84.

**Comment by keyone2693** [comment]
you didn't update the package on npm
