### ISSUE TITLE
[multiple]="false"  is not working .

### ISSUE THREAD

**Issue by prashant71ht** [peterfreeman/ngx-dropzone#43]
I am trying to invoked [multiple]="false" attribute, but it is not working for me , i am using 2.1.2 version.
Thanks in advance !!!

**Comment by peterfreeman** [comment]
Hey there,

what do you mean by it does not work?
If you're setting `multiple` to false, you can only select/drop one file at a time. If you want to limit the overall size of your `files` array you'll have to do this manually in the component.

**Comment by prashant71ht** [comment]
Yes right @peterfreeman , But in my case I did same thing like **[multiple]="false"** but it allows to add/drop  multiple file , and I tried your stack-blitz example and made the changes but  same problem also there.  I don't know why it not working.

**Comment by prashant71ht** [comment]
@peterfreeman this is my code
<ngx-dropzone [multiple]="false" (change)="onSelect($event)">
                              <ngx-dropzone-label>Drop your files here (or Click)</ngx-dropzone-label>
                              <ngx-dropzone-preview *ngFor="let f of files" [removable]="true" (removed)="onRemove(f)">
                                <ngx-dropzone-label>({{ f.name }}) &nbsp;({{f.type}})</ngx-dropzone-label>
                              </ngx-dropzone-preview>
                            </ngx-dropzone>

**Comment by prashant71ht** [comment]
@peterfreeman 
`<ngx-dropzone [multiple]="false" (change)="onSelect($event)">
                              <ngx-dropzone-label>Drop your files here (or Click)</ngx-dropzone-label>
                              <ngx-dropzone-preview *ngFor="let f of files" [removable]="true" (removed)="onRemove(f)">
                                <ngx-dropzone-label>({{ f.name }}) &nbsp;({{f.size}})</ngx-dropzone-label>
                              </ngx-dropzone-preview>
                            </ngx-dropzone> `

**Comment by Dewberrycat** [comment]
the same for me - i can drag and drop any quantity of files to dropzone

**Comment by peterfreeman** [comment]
@Dewberrycat This cannot be prevented. If you disable multiple files though, only one file will be in the `addedFiles` array, all others will be in `rejectedFiles`.

**Comment by JyotiPrkash** [comment]
@Dewberrycat  I know its too late to reply..but this multiple="false" can be done from .ts file. I did it by  making the `this.file = []` in this.onSelect function. like this everytime a new file is added..the dropzone will have only one file showing in UI and in this.files as well

**Comment by mwasigala** [comment]
@Dewberrycat  you can go around it by editing onSelect method 
`**files**:Files[ ]=[ ];                             //_declaring an array_

 **onSelect**(event) {
             this.files.push(...event.addedFiles);
             if(this.files.length > 1){       // _checking if files array has more than one content_
                   this.replaceFile();        // replace file
             }
    }

//**method for replacing  file**
 **replaceFile()**{
         this.files.splice(0,1);          // _index =0 , remove_count = 1_
 }`

**Comment by andshonia** [comment]
### 

-  @`_****_`

**Comment by rafaelnontol** [comment]
> @Dewberrycat I know its too late to reply..but this multiple="false" can be done from .ts file. I did it by making the `this.file = []` in this.onSelect function. like this everytime a new file is added..the dropzone will have only one file showing in UI and in this.files as well

Hi, this worked for me
Thank you
