### ISSUE TITLE
a11y improvements

### ISSUE THREAD

**Issue by linde12** [peterfreeman/ngx-dropzone#44]
Hello!

I have a tiny request to add an `id` input which would be forwarded to the native input control so that we can target it with a `<label for="id">` in order to make the page more accessible for people with visual impairments.

Same goes for `aria-describedby` and `aria-labelledby`, these should also just be forwarded to the native input.

**Comment by peterfreeman** [comment]
Hey there,

thanks for your feedback. Great idea, I put it on my ToDo list.

**Comment by peterfreeman** [comment]
Fixed in v2.2.0.
