### ISSUE TITLE
Disable click

### ISSUE THREAD

**Issue by njansenproquro** [peterfreeman/ngx-dropzone#48]
I think it would be usefull to add a feature to disable the click event.
I my case i have a transparent ngx-dropzone div, so a user can drag & drop file's anywhere on the page. But if someone accidently clicks somewhere on the page, the file dialog is opened.

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback. I added the `disableClick` property in v2.2.0.

Happy coding! 🤓

**Comment by njansenproquro** [comment]
Thanks for adding this feature. I've tested this and work great!
I've also noticed that if this property is true, you  can't manually call the showFileSelector method anymore. Is this intended behaviour?

**Comment by peterfreeman** [comment]
Hi @njansenproquro,

no, this behavior was not intended and is fixed in v2.2.2.

Happy coding! 🤓
