### ISSUE TITLE
Display images from server

### ISSUE THREAD

**Issue by shaytan-lana** [peterfreeman/ngx-dropzone#52]
Hi! A suggestion
Can you please make thumbnail display like this

this.imageSrc = this.sanitizer.bypassSecurityTrustUrl(img)
I searched a workaround how to display images from server in dropzone and the only problem I run into is that angular cant properly display file from URL, it needed to be sanitize

Thanks!

**Comment by peterfreeman** [comment]
Hi there,

you can [create a custom preview component](https://github.com/peterfreeman/ngx-dropzone/wiki/How-to-create-a-custom-preview-component%3F) for your use case to display files from URLs.
Please use the `ngx-dropzone-image-preview` as an inspiration.

If you'd like to, you can create a pull request for your new preview component.

Happy coding! 🤓

**Comment by shaytan-lana** [comment]
thaks)) will use custom preview component, didnt think of this

**Comment by KOSSOKO** [comment]
@shaytan-lana did you find a solution ? I have the same use case. After uploading my image I want also to display the image from the server using preview component.

**Comment by shaytan-lana** [comment]
@KOSSOKO hi) yeah, i found. I made custom component as preview for dropzone

`@Component({
  selector: 'custom-dropzone-preview',
  template: `
    <img [src]="imageSrc" />
    <ng-content select="ngx-dropzone-label"></ng-content>
    <ngx-dropzone-remove-badge *ngIf="removable" (click)="_remove($event)">
    </ngx-dropzone-remove-badge>
  `,
  styles: [`:host(){min-width:unset!important;max-width:unset!important;padding:0!important}:host():focus img,:host():hover img{opacity:.7}:host():focus ngx-dropzone-remove-badge,:host():hover ngx-dropzone-remove-badge{opacity:1}:host() ngx-dropzone-remove-badge{opacity:0}:host() img{max-height:100%;border-radius:5px;opacity:.8}:host() ::ng-deep ngx-dropzone-label{position:absolute;overflow-wrap:break-word}`],
  providers: [
    {
      provide: NgxDropzonePreviewComponent,
      useExisting: CustomDropzonePreviewComponent
    }
  ]
})
export class CustomDropzonePreviewComponent extends NgxDropzonePreviewComponent implements OnInit {

  imageSrc = "";
  
  constructor(sanitizer: DomSanitizer) {
    super(sanitizer);
  }

    ngOnInit() {
      this.imageSrc = this.file['url'];
    }
}`
I used this like an [custom preview](https://github.com/peterfreeman/ngx-dropzone/wiki/How-to-create-a-custom-preview-component%3F)

**Comment by KOSSOKO** [comment]
@shaytan-lana I tried your solution but when I upload the image I don't have the preview. 
In order to understand well your use case, when you upload an image you have the preview, then for example, when you refresh the page, you use the link ?
Or you have an static image, always the same ?
