### ISSUE TITLE
type mime application/xml

### ISSUE THREAD

**Issue by jylac** [peterfreeman/ngx-dropzone#53]
Hello,

Dropzone don't work with mime/type 'application/xml' type ?

Many thank for your library

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback. 
The accept type is forwarded to the native file input element so it should work like any file type. What are you trying to achieve?

Happy coding! 🤓

**Comment by thagh05t** [comment]
Hey,

What should the [accept] field look like? I get errors when trying to use it to restrict to images. I can provide the errors if need be, but it is likely that I am just syntactically doing something wrong.

**Comment by peterfreeman** [comment]
Hi there,

thanks for the comprehensive description. I'm glad you could solve your problem.
FYI: You could either use `accept="image/png"` like you did or `[accept]="'image/png'"` and provide a string value. This is due to Angular's input property bindings.

Happy coding! 🤓
