### ISSUE TITLE
On Angular 8, followed the instructions, but getting following exception.

### ISSUE THREAD

**Issue by amitchaudhary** [peterfreeman/ngx-dropzone#55]
ERROR Error: "Uncaught (in promise): Error: Template parse errors:
'ngx-dropzone-label' is not a known element:
1. If 'ngx-dropzone-label' is an Angular component, then verify that it is part of this module.
2. If 'ngx-dropzone-label' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("                        <ngx-dropzone (change)="onSelect($event)">

                                [ERROR ->]<ngx-dropzone-label>Drop it, baby!</ngx-dropzone-label>

                                <ngx-dropzon"): ng:///MainModule/CreateOrEditDriverModalComponent.html@42:32
Can't bind to 'removable' since it isn't a known property of 'ngx-dropzone-preview'.
1. If 'ngx-dropzone-preview' is an Angular component and it has 'removable' input, then verify that it is part of this module.
2. If 'ngx-dropzone-preview' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("/ngx-dropzone-label>

                                <ngx-dropzone-preview *ngFor="let f of files" [ERROR ->][removable]="true" (removed)="onRemove(f)">

                                    <ngx-dropzone-label>"): ng:///MainModule/CreateOrEditDriverModalComponent.html@43:78
'ngx-dropzone-label' is not a known element:
1. If 'ngx-dropzone-label' is an Angular component, then verify that it is part of this module.
2. If 'ngx-dropzone-label' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("r="let f of files" [removable]="true" (removed)="onRemove(f)">

                                    [ERROR ->]<ngx-dropzone-label>{{ f.name }} ({{ f.type }})</ngx-dropzone-label>

                               "): ng:///MainModule/CreateOrEditDriverModalComponent.html@44:36
'ngx-dropzone-preview' is not a known element:
1. If 'ngx-dropzone-preview' is an Angular component, then verify that it is part of this module.
2. If 'ngx-dropzone-preview' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("           <ngx-dropzone-label>Drop it, baby!</ngx-dropzone-label>

                                [ERROR ->]<ngx-dropzone-preview *ngFor="let f of files" [removable]="true" (removed)="onRemove(f)">

          "): ng:///MainModule/CreateOrEditDriverModalComponent.html@43:32
'ngx-dropzone' is not a known element:
1. If 'ngx-dropzone' is an Angular component, then verify that it is part of this module.
2. If 'ngx-dropzone' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("                <label for="Driver_AdhaarNo">{{l("AdhaarNo")}}</label>

                            [ERROR ->]<ngx-dropzone (change)="onSelect($event)">

                                <ngx-dropzone-label>Drop "): ng:///MainModule/CreateOrEditDriverModalComponent.html@41:28
syntaxError@http://localhost:4200/vendor.js:21312:22
./node_modules/@angular/compiler/fesm5/compiler.js/TemplateParser.prototype.parse@http://localhost:4200/vendor.js:31100:19
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._parseTemplate@http://localhost:4200/vendor.js:46410:37
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._compileTemplate@http://localhost:4200/vendor.js:46397:23
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._compileComponents/<@http://localhost:4200/vendor.js:46340:62
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._compileComponents@http://localhost:4200/vendor.js:46340:19
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._compileModuleAndComponents/<@http://localhost:4200/vendor.js:46250:19
then@http://localhost:4200/vendor.js:21303:77
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._compileModuleAndComponents@http://localhost:4200/vendor.js:46249:26
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype.compileModuleAsync@http://localhost:4200/vendor.js:46209:37
./node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js/CompilerImpl.prototype.compileModuleAsync@http://localhost:4200/vendor.js:85549:31
./node_modules/@angular/router/fesm5/router.js/RouterConfigLoader.prototype.loadModuleFactory/<@http://localhost:4200/vendor.js:92719:93
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._tryNext@http://localhost:4200/vendor.js:228899:27
./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype._next@http://localhost:4200/vendor.js:228889:18
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@http://localhost:4200/vendor.js:223594:18
subscribeToPromise/</<@http://localhost:4200/vendor.js:234357:28
./node_modules/zone.js/dist/zone.js/</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:4200/polyfills.js:12828:30
onInvoke@http://localhost:4200/vendor.js:74044:33
./node_modules/zone.js/dist/zone.js/</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:4200/polyfills.js:12827:36
./node_modules/zone.js/dist/zone.js/</Zone$1</Zone</Zone.prototype.run@http://localhost:4200/polyfills.js:12585:47
scheduleResolveOrReject/<@http://localhost:4200/polyfills.js:13326:38
./node_modules/zone.js/dist/zone.js/</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:12863:35
onInvokeTask@http://localhost:4200/vendor.js:74035:33
./node_modules/zone.js/dist/zone.js/</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:12862:40
./node_modules/zone.js/dist/zone.js/</Zone$1</Zone</Zone.prototype.runTask@http://localhost:4200/polyfills.js:12630:51
drainMicroTaskQueue@http://localhost:4200/polyfills.js:13043:39
"
    Angular 8

**Comment by peterfreeman** [comment]
Hi,

did you import the `NgxDropzoneModule` in your module?

**Comment by lmrisdal** [comment]
I'm getting the same message on Angular 8. NgxDropzoneModule is imported.
