### ISSUE TITLE
Remove icon is not appearing suddenly  

### ISSUE THREAD

**Issue by muhammadessarind** [peterfreeman/ngx-dropzone#57]
I am using ngx-dropzone in my project and suddenly remove icon disappeared from images when hovering on them, I don't know why it is happening and I am using latest version 2.2.2 

I have also removed all the CSS from the project but no luck.

**Comment by peterfreeman** [comment]
Hey there,

can you provide a minimal example on Stackblitz which demonstrates your behavior?
I assume there's just an error with the css being applied incorrectly.

Happy coding! 🤓
