### ISSUE TITLE
Reset dropzone from component not working

### ISSUE THREAD

**Issue by jigneshInd** [peterfreeman/ngx-dropzone#58]
Want to reset specific dropzone from the component by making variable empty like this :

this.files = [];

but it's not working, is there any other idea to reset dropzone from the component?

**Comment by peterfreeman** [comment]
Hey there,

please provide a code example on Stackblitz so I can reproduce your error.

Happy coding! 🤓

**Comment by jigneshInd** [comment]
Hi @peterfreeman,

Here is stackblitz, where I want to reset dropzone from component after  5 seconds 

https://stackblitz.com/edit/ngx-dropzone-demo

**Comment by peterfreeman** [comment]
Hi @jigneshInd,

after some testing I was able to fix your error by making just a small change.

```js 
setTimeout(() => {
  this.files = [];
}, 2000);
```

You see how I am using a lambda function over a default anonymous function? The difference is that the lambda function keeps the `this` object reference and therefore correctly clears the `files` array. If you want to know more about this you could have a look [here](https://gist.github.com/ericelliott/414be9be82128443f6df).

Happy coding! 🤓
