### ISSUE TITLE
ngx-dropzone-image-preview cannot assign File() object Error: sanitizing unsafe URL value data

### ISSUE THREAD

**Issue by manumohant** [peterfreeman/ngx-dropzone#59]
trying to create a page for details edit where i have an option to edit previously uploaded fiile. Tried to add the file to the list and it gave error 'sanitizing unsafe URL value data' but no provision to bypass this error

**Comment by peterfreeman** [comment]
Hey there,

could you please provide an example on Stackblitz.com to demonstrate the error?

Happy coding! 🤓

**Comment by almeidais** [comment]
I am also trying to figure out a way to create an array of type **File** using data that I'm getting from an API. No luck so far.
One way to reproduce it is to include OnInit in the demo.

```
  ngOnInit() {

    // I'm including only a part of a base64 code due to its big size
    const base64 = "data:image/png;base64,iVBORw0KGgoAAAANS...FfQAAAAASUVORK5CYII=";
    const imagemAsFile = new File([base64], 'Nome da Imagem');
    this.files.push(imagemAsFile);

  }
```

Error: 

> vendor.js:69959 WARNING: sanitizing unsafe URL value data:application/octet-stream;base64,ZGF0YTppbWFnZS9wbmc7YmFzZTY0LGlWQk...

**Comment by almeidais** [comment]
I was able to find a solution by converting the base64 string into an ArrayBuffer using the following function: 

 ```
 convertDataURIToBinary(dataURI: string) {
    var BASE64_MARKER = ';base64,';
    var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
    var base64 = dataURI.substring(base64Index);
    var raw = window.atob(base64);
    var rawLength = raw.length;
    var array = new Uint8Array(new ArrayBuffer(rawLength));

    for(var i = 0; i < rawLength; i++) {
      array[i] = raw.charCodeAt(i);
    }
    return array;
  }
```
Therefore, I created my File type image using:

```
const base64 = "data:image/png;base64,iVBORw0KGgoAAAANS...FfQAAAAASUVORK5CYII=";
const arrayBufferFromBase64 = convertDataURIToBinary(base64);
const imagemAsFile = new File([arrayBufferFromBase64], 'Nome da Imagem', {type: 'image/png'});
this.files.push(imagemAsFile);
```
Attention to the mime type! Although the creation of a new File allows for the omission of the mime type (third parameter), the image won't show and it will cause the sanitizing unsafe URL warning.

**Comment by peterfreeman** [comment]
The url sanitizing is done by Angular's `DomSanitizer` and independent of the component.
Using the `ArrayBuffer` seems like a good workaround.
