### ISSUE TITLE
Cant Upload a Video using this wrapper

### ISSUE THREAD

**Issue by millwala53** [peterfreeman/ngx-dropzone#6]
I tried to select a video file (.mp4 ) , it throws an error since the files added function doesnt return a file for vidoes. Works well with images.

**Comment by peterfreeman** [comment]
I'll look into it but it might take a few days. 😊

**Comment by peterfreeman** [comment]
I tested it and it returns the video in the File[]. It doesn't show videos in the preview, because that's not implemented. Can you post some code examples?

**Comment by peterfreeman** [comment]
Seems like this is no issue any more.
