### ISSUE TITLE
How to detect a folder drop or prevent a folder drop (accept files)

### ISSUE THREAD

**Issue by bppn** [peterfreeman/ngx-dropzone#61]
How can I detect or prevent a folder drop (aka acceptfiles)?

Thanks!

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback. 
Unfortunately, it is not possible to detect a folder drop consistently across all browsers at the moment. You can use the `[multiple]` attribute to drop multiple files at once.
If you want to add a feature to the component feel free to create a pull request.

Happy coding! 🤓
