### ISSUE TITLE
How do you get the image?

### ISSUE THREAD

**Issue by RSNFreud** [peterfreeman/ngx-dropzone#65]
Trying to make a custom image preview container but I do not understand how you get the image itself.

**Comment by peterfreeman** [comment]
Hi @RSNFreud,

if you did not already, have a look at the [guide](https://github.com/peterfreeman/ngx-dropzone/wiki/How-to-create-a-custom-preview-component%3F) on how to create a custom preview component.

To get the image have a look at my [reference implementation](https://github.com/peterfreeman/ngx-dropzone/blob/master/projects/ngx-dropzone/src/lib/ngx-dropzone-preview/ngx-dropzone-image-preview/ngx-dropzone-image-preview.component.ts) of the image preview. If you inherit from `NgxDropzonePreviewComponent` you get access to the `readFile()` method which will return the image as base64 string that you can assign directly to an `<img [src]>` tag.

Happy coding! 🤓
