### ISSUE TITLE
The options are not working correctly

### ISSUE THREAD

**Issue by ShirinShirinak** [peterfreeman/ngx-dropzone#68]
So I copied the code from here and I made two changes to it. I wanted to be able to accept only 1 file (I was gonna get rid of the for loop later), and also I wanted to only accept one file type (csv). After I add the [accept] and [multiple] options, I can't drop any files in the dropzone any more, not even a csv file. What should I do? 

I had a look at the demo and made the same change there and demo stopped working too.
@peterfreeman 

```
<ngx-dropzone (change)="onSelect($event)" [accept]='csv'
            [multiple]='false'>
                <ngx-dropzone-label>Drop your CSV file here!</ngx-dropzone-label>
                <ngx-dropzone-preview *ngFor="let f of files" [removable]="true" (removed)="onRemove(f)">
                    <ngx-dropzone-label>{{ f.name }} ({{ f.type }})</ngx-dropzone-label>
                </ngx-dropzone-preview>
            </ngx-dropzone>
```

**Comment by peterfreeman** [comment]
Hi @ShirinShirinak,

thanks for your feedback. You can specify the `accept` attribute for csv files in two ways:
* `accept="text/csv"`
* `[accept]="'text/csv'"` (with square brackets and single quotes to make it a string

Happy coding! 🤓
