### ISSUE TITLE
Cannot Call ngx-dropzone in sub components

### ISSUE THREAD

**Issue by jokerxvier06** [peterfreeman/ngx-dropzone#7]
Hi I'm a beginner in angular. I cannot call <ngx-dropzone></ngx-dropzone> in my sub components. Why is it? I can only make work in my app.component.  How can I fixed this?

**Comment by peterfreeman** [comment]
Hi. 😊
Make sure you follow the tutorial on [angular.io](https://angular.io/tutorial) if you're a beginner.
Your problem might be that you don't import the NgxDropzoneModule into your submodule. Do you get any errors in the console or what's the problem?

**Comment by peterfreeman** [comment]
Seems like this is no issue anymore, so I'm closing it.
