### ISSUE TITLE
Image height and width

### ISSUE THREAD

**Issue by hhetland** [peterfreeman/ngx-dropzone#74]
How do I get the image height and width?

Thanks.. :)

**Comment by peterfreeman** [comment]
Hi @hhetland,

do you want to get the dimensions (height and width) of the image the user dropped?
This library provides no function for this as it's not the intention of this package.
See this StackOverflow [link](https://stackoverflow.com/a/20569043) for an example.

Happy coding! 🤓

**Comment by hhetland** [comment]
I was hoping for some magic in connection with the uploader / preview :-)
Tried different things bit could not get it working.

I fixed it by getting the dimensions and adding them to the file meta in Firebase Storage after saving. Works nicely 

Thanks
