### ISSUE TITLE
'ngx-dropzone' is not a known element

### ISSUE THREAD

**Issue by emerdev812** [peterfreeman/ngx-dropzone#76]
I get error something like this.
***
Uncaught Error: Template parse errors:
'ngx-dropzone' is not a known element:
***

I just add NgxDropzoneModule into app.module.ts.
My angular project version is 5.0

**Comment by peterfreeman** [comment]
Hi there,

does this problem still persist?
Make sure you're importing the DropzoneModule into the module where you use the component.

pf
