### ISSUE TITLE
NgxDropzoneChangeEvent  type and rejection issues

### ISSUE THREAD

**Issue by MarineMarin** [peterfreeman/ngx-dropzone#80]
Hello,
Contrary to what is explained in the readme, the rejectedFiles property of the NgxDropzoneChangeEvent is of type File and not RejectedFile, so we can't access the reason property...
Or am I missing something?

Moreover, when I set multiple to false and I try to add a second file to the dropzone, this second file shows up in the addedFiles property of the NgxDropzoneChangeEvent and not in the rejectedFiles property, while it should be there, with the reason "no_multiple"...

**Comment by peterfreeman** [comment]
HI there,

could you please provide a minimal working example which can be used to reproduce the first error?
This never occurred yet.

Concerning the second problem, this is actually intended behavior. The `multiple` property only applies to each drop event on its own. After that, handling the dropped file(s) is left over to the user. 
So in your case, you would want to add some logic to check if your one single file is already set. If so, then throw an error.

pf
