### ISSUE TITLE
Export NgxDropzoneService as a public API

### ISSUE THREAD

**Issue by picturelink** [peterfreeman/ngx-dropzone#87]
I've had to implement my own component as I needed to add hittest functionality, but rather than reinvent the wheel I thought I'd use `NgxDropzoneService` to do the file parsing (I'm using NgxDropzone elsewhere in the project). Unfortunately I've discovered that it can't be used as is.

It would be incredibly useful if the `NgxDropzoneService` could be publicly exposed.

**Comment by peterfreeman** [comment]
Hey there,

thanks for your feedback. I'm planning to work on v3 of the component right now and will consider this.
Until then, I recommend you have a look at the code an maybe copy it for your own project?

Happy coding! 🤓
