### ISSUE TITLE
Image Preview is not being replaced when new image is selected

### ISSUE THREAD

**Issue by phoebelord** [peterfreeman/ngx-dropzone#89]
### Issue and Steps to Reproduce
minimal example here https://stackblitz.com/edit/ngx-dropzone-pjuzbu?file=src/app/app.component.ts

1. set up dropzone that only allows one image at one time
2. upload an image
3. **click on the dropzone** (not the cross) and select a different image from the file explorer 

**The file name on the preview will be updated but the image preview is not**

#### Actual

After 1st image is selected - _derp.png_
![step1](https://user-images.githubusercontent.com/47673521/100631663-e0018500-3323-11eb-8393-849947334a97.png)

After new image is selected - _troll.png_
**filename is updated but image is not**
![step2](https://user-images.githubusercontent.com/47673521/100631683-e55ecf80-3323-11eb-9606-ba183064f0fe.png)

#### Expected
expected image to also update
![expected](https://user-images.githubusercontent.com/47673521/100631705-eabc1a00-3323-11eb-9749-56b6591b0912.png)

**Comment by peterfreeman** [comment]
Fixed in v3.0.0.
