### ISSUE TITLE
Doesn't support Ivy rendering

### ISSUE THREAD

**Issue by OrionStark** [peterfreeman/ngx-dropzone#90]
Guys is it really fully supported with the ivy rendering or not?. I'll ready to re-installing the node_modules but nothing seems to be changed or fixed. Can you guys help me?

**Comment by OrionStark** [comment]
Any update?

**Comment by peterfreeman** [comment]
What exactly do you mean? Do you get any error messages or other problems using the library?

**Comment by OrionStark** [comment]
@peterfreeman exactly.
`This likely means that the library (ngx-dropzone) which declares NgxDropzoneModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.`

**Comment by peterfreeman** [comment]
Hey @OrionStark,

I released v3.0.0, which is now using Angular 11.
Does your problem still persists with this version?

**Comment by OrionStark** [comment]
@peterfreeman Hi, Thanks for the update. It's cool. I'm going to close this issue right now.

**Comment by alhazmy13** [comment]
this issue still exists with anuglar `11` and ngx-dropzone `3.0.0`
```
    Error: node_modules/ngx-dropzone/lib/ngx-dropzone.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of ResumeModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (ngx-dropzone) which declares NgxDropzoneModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and updat
e if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    1 export declare class NgxDropzoneModule {

```

**Comment by bayramerenn** [comment]
I got the same error too. Can you help me?

  This likely means that the library (ngx-dropzone) which declares NgxDropzoneModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    1 export declare class NgxDropzoneModule {
