### ISSUE TITLE
How to set default image from api's

### ISSUE THREAD

**Issue by ultimateakash** [peterfreeman/ngx-dropzone#91]
I have integrated ngx dropzone in my project its working fine. but on the edit product page, I need to show images submitted by the user from add product form.
Images coming from API. so how can i show these images on the dropzone please help me.

**Comment by peterfreeman** [comment]
I would suggest the following:
* Download the image data from your API as a `base64` string
* Display the image using an html `<img>` tag. Use the [preview implementation](https://github.com/peterfreeman/ngx-dropzone/blob/5440d45602152d4101676fac0af53ea46fcc70fe/projects/ngx-dropzone/src/lib/ngx-dropzone-preview/ngx-dropzone-image-preview/ngx-dropzone-image-preview.component.ts#L30) as an example

Happy coding! 🤓

**Comment by keyone2693** [comment]
just add this future please review 
https://github.com/peterfreeman/ngx-dropzone/pull/96

**Comment by NishadAbdul** [comment]
There should be a way to default preview component with fileName and fileSize from server response. This data can be pushed to the addedFiles to display.
