### ISSUE TITLE
accept parameter

### ISSUE THREAD

**Issue by MiguelHAngelH** [peterfreeman/ngx-dropzone#92]
Hi everyone, I am implementing the pacacke in angular 11, and the accept parameter doesn't work 
**

> [maxFileSize]="'2000000'" [accept]="'image/*'"

**
I put that, and when I upload a PDF 
I get an error of Type **reason=size** 
and not **reason=type**.

**Comment by peterfreeman** [comment]
Hey there, 

could you provide a Stackblitz example showing your problem?
In your code you set the `maxFileSize` as type string, you should fix this anyway.

Happy coding! 🤓

**Comment by moeali1010** [comment]
try [accept]="'application/pdf'"
