### ISSUE TITLE
Are there any restrictions for the use of ngx-dropzone?

### ISSUE THREAD

**Issue by 9Dann7** [peterfreeman/ngx-dropzone#97]
Hello! 

Currently I'm working on a project for my school, but we need to use open source libraries/components, etc. 

For now we are using libraries/components with MIT license, but I'm curious because at the license section on the README.md says "MIT © Peter Freeman" and I don't know if there are some restrictions. 

Thank you!

**Comment by peterfreeman** [comment]
Hey @9Dann7,

the MIT license lets you use the dropzone for your school project without any restrictions.

Happy coding! 🤓
