### ISSUE TITLE
How to customize preview ?

### ISSUE THREAD

**Issue by coNNectGan** [peterfreeman/ngx-dropzone#99]
![image](https://user-images.githubusercontent.com/47696394/111838166-e7c95180-8933-11eb-81a1-e90d955fde52.png)
Hi =D, I'm new to angular, may I ask
1) how to customize the text (middle of the picture)?
2) how to show the file size?
3) ngProjectAs="ngx-dropzone-preview"  , what is this use for?
Hope to get the answer as soon as possible. Really thank you

**Comment by peterfreeman** [comment]
Hi there,

please use this example as a starting point:

```html
<ngx-dropzone-preview *ngFor="let file of files">
	<ngx-dropzone-label>Your text here! ({{ file.size }})</ngx-dropzone-label>
</ngx-dropzone-preview>
```

The `ngProjectAs="ngx-dropzone-preview"` allows a component to be content-projected and treated the same way as the `NgxDropzonePreviewComponent`. All inheriting components require this parameter.
You can read more about Angular content projection [here](https://medium.com/ignite-ui/using-ng-content-ngprojectas-1664d7c1d3b).

Happy coding! 🤓
